version: "3.9"
services:
  app:
    container_name: bot
    image: bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TOKEN=${TOKEN}
      - PREFIX=${PREFIX}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  lavalink:
    image: fredboat/lavalink:77a3bd81
    container_name: bot-lavalink
  db:
    image: mongo:5.0.6
    container_name: bot-db
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=${DB_PORT}
    volumes:
      - ./database:/database
